# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 14:23
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import i18nfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pretix_additional_links', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='link_in_footer',
            field=models.BooleanField(default=False, verbose_name='Zeige die URL auf der Event Seite'),
        ),
        migrations.AlterField(
            model_name='links',
            name='link_on_frontpage',
            field=models.BooleanField(default=False, verbose_name='Zeige die URL im Footer'),
        ),
        migrations.AlterField(
            model_name='links',
            name='slug',
            field=models.CharField(db_index=True, help_text='Used to genereated the meaning within the Plugin. You can´t change it afterwards.', max_length=150, validators=[django.core.validators.RegexValidator(message='The slug may only contain letters, numbers, dots and dashes.', regex='^[a-zA-Z0-9.-]+$')], verbose_name='URL Slug'),
        ),
        migrations.AlterField(
            model_name='links',
            name='title',
            field=i18nfield.fields.I18nCharField(verbose_name='URL title'),
        ),
        migrations.AlterModelOptions(
            name='links',
            options={'ordering': ['position', 'title']},
        ),
        migrations.AddField(
            model_name='links',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='links',
            name='link_url',
            field=i18nfield.fields.I18nCharField(verbose_name='URL Link'),
        ),
        migrations.AlterField(
            model_name='links',
            name='link_in_head',
            field=models.BooleanField(default=False, verbose_name='Zeige die URL im Header an'),
        ),
    ]
